name: Deploy to GitHub Pages
on:
  push:
    branches: [main] # 当你推送到 main 分支时触发
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm run build # 这里执行打包
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 打包后的文件夹名，Vue/Vite通常是dist
